name: test_poc

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2
            # Setup java 17 to be default (sonar-scanner requirement as of 5.x)
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Sonar Scan
        uses: warchant/setup-sonar-scanner@v7
      - name: SonarQube Scan
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=aem-test1 -Dsonar.projectName='aem-test1' -Dsonar.host.url=${{secrets.SOANR_HOST_URL}} -Dsonar.token=${{secrets.SONAR_TOKEN}}
