name: Sonar-Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: aem-runner
    steps:
      - name: Checking out
        uses: actions/checkout@v2
            # Setup java 17 to be default (sonar-scanner requirement as of 5.x)
      - name: Sonar test
        run: |
          export PATH=/opt/maven/apache-maven-3.9.6/bin:$PATH && export JAVA_HOME=/opt/java/jdk-17.0.2 && mvn clean install && mvn clean package sonar:sonar -Dsonar.host.url="http://13.201.33.163:9000" -Dsonar.projectKey=AEM-WEEKEND-7 -Dsonar.projectName='AEM-WEEKEND-7' -Dsonar.token=sqa_a51390374c149203754221835b8232248ed0d2cc
