name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
      
    - name: Build with Maven
      run: mvn clean install -B
        - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        host: 'http://13.233.186.160:9000/'
        login: 'sqa_eeefad7db086885c55080a8f0a89618c5ea929b3'

